### ISSUE TITLE
handle `//` comments

### ISSUE THREAD

**Issue by Heather** [erikd/hjsmin#19]
example

``` js
(function(global) {
    
// Data type check

function isObject(value, ignoreArray) {
    return typeof value === 'object' && value !== null;
}
```

**Comment by erikd** [comment]
If I change that comment to `/* Data type check */` it still doesn't parse, but the following:

    // Data type check
    function isObject(value, ignoreArray) {
        // Comment
        return typeof value === 'object' && value !== null;
    }

parses and seems to minimize correctly.

Please retest.
