### ISSUE TITLE
hjsmin incorrect minification

### ISSUE THREAD

**Issue by fgaray** [erikd/hjsmin#22]
I just found out that hjsmin performs an incorrect minification of bootstrap-datepicker

In Firefox and Chrome it gives this error:
~~~
SyntaxError: expected expression, got keyword 'else'1 autogen-unjVjs7z.js:4:387
~~~ 

Tested in hjsmin 0.1.5.0

You can use this files to check it.

https://gist.github.com/fgaray/0a08a3f4ab3c01f2d7c9

I managed to get a minimal example:

~~~{.javascript}
if(1)
    ;
else if(2){
    3;
}
~~~

Incorrect result

~~~{.javascript}
if(1)else if(2)3
~~~

**Comment by fgaray** [comment]
It seems that I reported this issue in the incorrect library, this should be in https://github.com/erikd/language-javascript

**Comment by erikd** [comment]
I'll close this, when I fix it in language-javascript and bump the dependency here.

Thanks for the report.

**Comment by erikd** [comment]
Actually was in hjsmin and not it language -javascript.

Please test. If you can confirm this version works, I'll push a new version to Hackage.

**Comment by fgaray** [comment]
Yes, that fixed the issue, thank you!

**Comment by erikd** [comment]
New version 0.1.5.1 is on Hackage. Thanks.
