### ISSUE TITLE
Support language-javascript-0.6

### ISSUE THREAD

**Issue by felixonmars** [erikd/hjsmin#25]
`hjsmin` doesn't compile with latest `language-javascript-0.6.0.0` atm, it would be nice to support the new version:

```
Text/Jasmine/Pretty.hs:9:36:
    Module `Language.JavaScript.Parser' does not export `JSNode(..)'

Text/Jasmine/Pretty.hs:9:47:
    Module `Language.JavaScript.Parser' does not export `Node(..)'
```

**Comment by erikd** [comment]
Wow, I released the new version of `language-javascript` less than 3 hours ago! The cabal file for hjsmin does have requirement of `language-javascript < 0.6`.

However, I am working on it. I just want to make sure there are no bugs in switching to the minfier that is now part of `language-javascript`. I should have a this sorted out by the end of the weekend.

**Comment by felixonmars** [comment]
I see, thank you for the fast response :)

**Comment by erikd** [comment]
Well it turned out the testing was pretty trivial and found no issues whatsoever.

Version 0.2.0.0 just released to Hackage.
