### ISSUE TITLE
Hjsmin not compiling

### ISSUE THREAD

**Issue by omangin** [erikd/hjsmin#26]
Hi, while trying to install the package (both from `cabal install hjsmin` and from cloning the repository and `cabal clean && cabal configure && cabal build`) I get the following failure:

```
Building hjsmin-0.2.0.1...
Preprocessing library hjsmin-0.2.0.1...
[1 of 2] Compiling Text.Jasmine.Pretty ( Text/Jasmine/Pretty.hs, dist/build/Text/Jasmine/Pretty.o )
[2 of 2] Compiling Text.Jasmine     ( Text/Jasmine.hs, dist/build/Text/Jasmine.o )
Preprocessing executable 'hjsmin' for hjsmin-0.2.0.1...
[1 of 2] Compiling Text.Jasmine     ( Text/Jasmine.hs, dist/build/hjsmin/hjsmin-tmp/Text/Jasmine.o )
[2 of 2] Compiling Main             ( hjsmin.hs, dist/build/hjsmin/hjsmin-tmp/Main.o )

hjsmin.hs:24:13: error:
    • Variable not in scope: (<>) :: InfoMod a6 -> InfoMod a7 -> t2
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)

hjsmin.hs:28:13: error:
    • Variable not in scope:
        (<>) :: t2 -> InfoMod a8 -> InfoMod Options
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)

hjsmin.hs:34:22: error:
    • Variable not in scope:
        (<>) :: Mod f0 a0 -> Mod f1 a1 -> Mod ArgumentFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)

hjsmin.hs:37:21: error:
    • Variable not in scope: (<>) :: Mod f2 a2 -> Mod f3 a3 -> t1
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)

hjsmin.hs:38:21: error:
    • Variable not in scope: (<>) :: t1 -> Mod f4 a4 -> t0
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)

hjsmin.hs:39:21: error:
    • Variable not in scope:
        (<>) :: t0 -> Mod f5 a5 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
```

I'm using cabal 1.24.0.0 with ghc 8.0.1 on archlinux.

Thanks

**Comment by erikd** [comment]
Version 0.2.0.2 uploaded to Hackage.

**Comment by ygale** [comment]
We are still experiencing this issue, because we currently cannot use `language-javascript >= 0.6` which is required by `hjsmin >= 0.2`. It's only a problem for versions of `hjsmin` that have `hjsmin.hs`, i.e., starting with version 0.1.5.0.

The underlying problem is that `optparse-applicative` stopped exporting `<>` starting in version 0.13.0.0. Could you please add this constraint to pre-0.2.0.2? That could be done either by editing the `optparse-applicative` constraint on hackage and adding the upper bound `"< 0.13.0.0"` for `hjsmin` versions `[0.1.5.0 .. 0.2.0.1]`, or by uploading a new `hjsmin` version `0.1.5.4` identical to `0.1.5.3` except for the addition of that upper bound. Thanks!

**Comment by erikd** [comment]
I've edited the constraints form for 0.1.5.3. Please test.

**Comment by ygale** [comment]
Thanks! But unfortunately, no. Cabal decided to leave `optparse-applicative` at 0.13.0.0 and instead bump back `hjsmin` to 0.1.5.2.

What we want is to hold back `optparse-applicative` until our next (hopefully soon) GHC upgrade and use the latest `hjsmin` we can, which would be 0.1.5.3. So unless you release 0.1.5.4 with the `Data.Monoid` import, I think we'll ensure that by using a `cabal.config` constraint. Then we'll be fine.

**Comment by erikd** [comment]
Version 0.1.5.4 is now on Hackage and it supports `optparse-applicatve == 0.13.*` Please test.
