### ISSUE TITLE
hjsmin-0.2.0.3 test suite failure

### ISSUE THREAD

**Issue by peti** [erikd/hjsmin#32]
Citing from https://hydra.nixos.org/build/103546286:

~~~
Running 1 test suites...
Test suite test-cli: RUNNING...
test-cli: /build/hjsmin-0.2.0.3/dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
Test suite test-cli: FAIL
~~~

It looks like maybe there is a file or directory missing from the release tarball? Or maybe some other hard-coded path does not exist?

**Comment by erikd** [comment]
I suspect that is due to using an old version of cabal. I am using cabal version 3.0 and the follow works fine:
```
cd /tmp/
git clone https://github.com/erikd/hjsmin
cd hjsmin/
cabal build 
cabal test --test-show-details=direct
```

**Comment by peti** [comment]
> git clone https://github.com/erikd/hjsmin

Keep in mind that I am not building from a git checkout. I compile a release tarball from Hackage, which may not have the same files as your git repo does.

**Comment by svmhdvn** [comment]
This issue still exists when building with the nixpkgs haskell infrastructure on the latest haskell-updates branch (after removing the dontCheck override to ensure that tests are run during the build):

```
Running 1 test suites...
Test suite test-cli: RUNNING...
test-cli: /build/hjsmin-0.2.0.4/dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
Test suite test-cli: FAIL
Test suite logged to: dist/test/hjsmin-0.2.0.4-test-cli.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/sdkcj127abl0fs6cfi0mfqzax2g1s5ws-hjsmin-0.2.0.4.drv' failed with exit code 1
error: build of '/nix/store/sdkcj127abl0fs6cfi0mfqzax2g1s5ws-hjsmin-0.2.0.4.drv' failed
```

**Comment by erikd** [comment]
I don't (willingly) use Nix. Unless you can recreate this from a git checkout or the Hackage tarball I will not be spending any time on this.
