### ISSUE TITLE
handle async await keywords

### ISSUE THREAD

**Issue by setop** [erikd/hjsmin#35]
After further investigation on erikd/language-javascript#136, it seems that hjsmin does not hangle async/await at all.

`async function` is transformed into `async;function` which cause the JS engine to fail.

Same `await some_code` is transformed into `await;some_code` which cause the JS engine to fail too.

**Comment by erikd** [comment]
Please provide a small JS snippet that uses both of these constructs.

**Comment by setop** [comment]
JS code : 

```
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });

  let result = await promise; // wait until the promise resolves (*)

  console.log(result); // "done!"
}

f();
```
HTML code:

```
<html>
</html>
<script src="async_await.js"></script>
```

When loaded, just print "done!" in the console

JS minimizd by hjsmin 0.2.0.4

```
async;function f(){let promise=new Promise((resolve,reject)=>setTimeout(()=>resolve("done!"),1000));let result=await;promise;console.log(result)};f()
```
Note the semi columns after `async` and `await`.
When used, give `ReferenceError: async is not defined`.

Can be manually fixed, removing those semi-columns:

```
async function f(){let promise=new Promise((resolve,reject)=>setTimeout(()=>resolve("done!"),1000));let result=await promise;console.log(result)};f()
```

It works.

**Comment by erikd** [comment]
`hjsmin` built against version `0.7.1.0` of `language-javascript` should correctly minify the example you posted.
