### ISSUE TITLE
support for text 2.0 needed

### ISSUE THREAD

**Issue by simonmichael** [erikd/hjsmin#38]
Requiring text < 2 is keeping hjsmin and things depending on it (yesod-static, hledger-web..) out of stackage nightly. Noting this here since I don't see any discussion.

**Comment by simonmichael** [comment]
Hello @erikd, I enabled text 2 support with #39. No real code changes needed. Would you consider merging this and publishing a new release on Hackage ?

**Comment by simonmichael** [comment]
Ping, @erikd ?

**Comment by erikd** [comment]
Sorry. FIx is on `master` and released to Hackage.

**Comment by simonmichael** [comment]
Thank you very much!

**Comment by simonmichael** [comment]
It will also be in the next stackage nightly.
